services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - TZ=Australia/Sydney
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
      - ./app-logs:/app/logs  # Mount point for Winston logs
    restart: unless-stopped

